model:
  model_path: 
  type: GraphLayoutNet
  mixed_precision_flag: false
  focal_loss_flag: true
  max_pair_num: 50000
  cnn_emb_feat: 512
  box_emb_feat: 256
  gcn_out_feat: 512
  text_emd_feat: 0
  num_polar_bins: 8
  polar_emb_feat: 6
  #  vocab_path: 
  rope_max_length: 32
  rope_emb_feat: 512
  k_nearest_num: 10
  text_hidden_dim:
  encode_text_type: none
  graph_type: DGCNN   #DGCNN/GravNet
  graph_layer_num: 1
  norm_box_flag: true
  cnn_flag: true
  cnn_backbone_type: resnet18 #resnet18/resnet50/fasterrcnn_resnet50_fpn_v2
  gnn_res_flag: true
  relation_flag: true
  rope_flag: false
  polar_flag: false
  fc_flag: true
  node_class_flag: true
  height: 400
  width: 400
  class_list: ['Text', 'Title', 'Figure', 'Table', 'List', 'Header', 'Footer']
  class_map: {}

predictor:
  img_paths:
  img_label_paths:
  img_input_dirs:
    - /open-dataset/OD-layout/publaynet/val
  img_label_dirs:
    - /open-dataset/OD-layout/publaynet_entity_graph_labels/val
#  img_input_dirs:
#    - /open-dataset/OD-layout/DocLayNet_core
#  img_label_dirs:
#    - /open-dataset/OD-layout/DocLayNet_core_graph_labels/val
  save_dir:
  aug_flag: false
  do_visualize: false
  save_coco_result: true
  pad_flag: false
  post_processor:
    type: DefaultPostProcessor
    delete_dif_cls: false
    pair_score_threshold: 0.55
trainer:
  optimizer:
    optimizer_type: "adam"
    lr: 1e-5
  scheduler:
    scheduler_type: "stairs"
    warmup_epochs: 2
  loss:
    type: GraphLayoutLoss
    edge_type: CrossEntropyLoss
    edge_contrastive_loss_flag: false
    node_contrastive_loss_flag: false
    class_weight_flag: true
    node_weight: 
    edge_weight: 
    #    edge_type: FocalLoss
    gamma: 2 #focal loss
    alpha:
    size_average: true #focal loss
    loss_weight: 1
  metric:
    type: GraphLayoutMetric
  epochs: 20
  save_dir: /tmp/
  tensorboard_dir: /tmp/
  save_epoch_freq: 1
  save_step_freq: 0
  print_freq: 10
  eval_print_freq: 10
  display_freq: 20
datasets:
  train:
    dataset:
      type: GraphLayoutDataset
      crop_img_flag: false
      data_root:
      label_root:
    num_workers: 0
    batch_size: 4
    collate_fn:
      type: GraphCollateFn
      debug_cell: false
      pad_flag: false
  eval:
    dataset:
      data_root:
      label_root:
    collate_fn:
      debug_cell: false