base: config/graph_net/train_layout_graph_funsd.yaml
model:
  model_path:
  k_nearest_num:
  rope_flag: false
trainer:
  loss:
    node_weight: [1.31, 1.0, 6.45, 2.62]
    edge_weight: [1.0, 55.0]
  save_dir: funsd_entity/
  tensorboard_dir: funsd_entity/tensorboard/
datasets:
  train:
    dataset:
      type: GraphLayoutEntityDataset
      data_root:
        - /open-dataset/OD-layout/FUNSD/training_data
      label_root:
        - /open-dataset/OD-layout/FUNSD_entity_graph_labels/training_data
    collate_fn:
      type: GraphEntityCollateFn
  eval:
    dataset:
      data_root:
        - /open-dataset/OD-layout/FUNSD/testing_data
      label_root:
        - /open-dataset/OD-layout/FUNSD_entity_graph_labels/testing_data
